apiVersion: v1
kind: Config
clusters:
  - name: minikube
    cluster:
      server: https://127.0.0.1:8443
      insecure-skip-tls-verify: true
contexts:
  - name: minikube
    context:
      cluster: minikube
      user: minikube
current-context: "minikube"
preferences: {}
users:
  - name: minikube
    user:
      token: "placeholder"
